### ISSUE TITLE
package breaks if DS is not defined

### ISSUE THREAD

**Issue by Schlaefer** [cakephp/filesystem#1]
As I understand it is encouraged to use the filesystem as standalone package without the cake core. 

For that scenario it would be nice if the package wasn't depended on 'DS' defined in the environment.

**Comment by jadb** [comment]
`DS` is just an abbreviation to `DIRECTORY_SEPARATOR` - want to submit a PR replacing all instances of `DS` with the longer version?

**Comment by Schlaefer** [comment]
Ok. Against cakephp/cakephp master?

**Comment by ADmad** [comment]
@Schlaefer Yes
